import type { Metadata } from "next"
import { TrendingUp, Clock, BarChart3, Users } from "lucide-react"
import { PageHero } from "@/components/marketing/PageHero"
import { Reveal } from "@/components/marketing/Reveal"
import { CTA } from "@/components/marketing/CTA"

export const metadata: Metadata = {
  title: "Co-Marketing Calendar | Momenties",
  description: "Plan your co-marketing calendar with partner identification, campaign coordination, content co-creation, and performance reviews. Build partnerships that grow both audiences.",
}

const pillars = [
  {
    icon: TrendingUp,
    title: "Partner Identification & Pipeline Calendar",
    body: "Co-marketing partner identification criteria: complementary audience (no direct competition), comparable audience size (within 3× of yours), proven content quality, aligned brand values, and a clear co-benefit hypothesis (what each side gains). Build a rolling quarterly pipeline of 10–15 potential partners — research, qualify, and prioritize by potential reach and audience fit. Outreach cadence: initial email → 5-day follow-up → decision call → partnership brief within 2 weeks of verbal agreement. Partner tiering: Tier 1 (full integrated campaign — joint webinar, co-authored guide, email cross-promotion), Tier 2 (content swap — newsletter inclusion, social co-post), Tier 3 (distribution only — mention, link exchange). Calendar 1 Tier-1 and 2–3 Tier-2 partnerships per quarter.",
  },
  {
    icon: Clock,
    title: "Campaign Coordination & Content Co-Creation Calendar",
    body: "Co-marketing campaign lead time: Tier-1 integrated campaigns need 8–10 weeks from agreement to launch. Campaign brief shared at week 1 — includes audience split, content ownership, promotion responsibilities, link tracking, and success metrics. Content co-creation: co-authored guide (both teams contribute sections, one team leads editorial), joint webinar (one host from each brand, one team runs technical production), research report (both teams contribute customer survey participants, neutral third-party framing). Creative review: 2-week approval window per side — build into timeline. Brand guidelines exchange at brief stage — both brands must approve all co-branded assets before publish.",
  },
  {
    icon: BarChart3,
    title: "Cross-Promotion & Distribution Calendar",
    body: "Distribution planning: each partner owns their email list and social audience — coordinate simultaneous send timing (same week, ideally same day) to maximize mutual exposure. Email cross-promotion: dedicated send vs mention (mention to 100% list, dedicated send to engaged segment only — 30-day opens). Social co-posting: coordinate posting time, tag partner account, share each other&apos;s post within 24 hours. Landing page: one team hosts the gated asset, both teams drive traffic — UTM parameters track contribution by partner. Joint press release: one team pitches, one team amplifies — agree in brief which team leads PR. Distribution review 48 hours post-launch: compare traffic, signups, and engagement by source.",
  },
  {
    icon: Users,
    title: "Performance Review & Relationship Maintenance Calendar",
    body: "Post-campaign review: 7-day debrief with partner — leads generated by each side, audience overlap (any email list crossover?), content performance, and any unexpected complications. Monthly partner relationship touchpoint: share a relevant resource or make an introduction (non-ask outreach maintains relationship). Quarterly co-marketing retrospective: rank all active partnerships by leads generated per campaign, audience growth, and brand exposure value — renew high-performers, wind down low-performers. Annual partnership audit: update partner tiers based on performance data, identify new partnership candidates in categories that performed well. Track all co-marketing attributions in a shared UTM/CRM log — co-marketing attribution is notoriously hard to track without systems.",
  },
]

const timeline = [
  {
    phase: "Month 1",
    label: "Partnership Pipeline Build",
    description:
      "Research and identify 15–20 potential co-marketing partners, qualify by audience fit and reach, prioritize top 5 for outreach, draft outreach email templates, and identify first partnership type (webinar, guide, newsletter swap) to pilot.",
  },
  {
    phase: "Month 2–3",
    label: "First Co-Marketing Campaign',",
    description:
      "Close first Tier-1 partnership, execute first co-marketing campaign (joint webinar recommended for first partnership — lower production burden), measure results, write post-campaign debrief, and close 2–3 Tier-2 partnerships (newsletter swaps or social co-posts).",
  },
  {
    phase: "Month 4–6",
    label: "Scale to Quarterly Cadence',",
    description:
      "Run one Tier-1 campaign per quarter, maintain 2–3 active Tier-2 partnerships per month, begin tracking leads by partner contribution, and adjust partner mix based on performance data from first 90 days.",
  },
  {
    phase: "Month 7–12",
    label: "Systematize & Expand',",
    description:
      "Build co-marketing playbook from first three campaigns, identify new partnership categories (integrations, communities, media), begin reciprocal referral program with top partners, and conduct annual partnership audit and roadmap for next year.",
  },
]

const metrics = [
  { label: "Leads per co-marketing campaign", benchmark: "Track by partner — Tier-1 campaign target: 200–500 net-new leads" },
  { label: "Email list growth from co-marketing", benchmark: "5–15% of leads from co-marketing should be net-new to your list" },
  { label: "Co-marketing CAC vs owned-channel CAC", benchmark: "Co-marketing should be 30–50% lower CAC than comparable paid channels" },
  { label: "Partner response rate", benchmark: "≥30% outreach acceptance rate from qualified Tier-1 targets" },
  { label: "Content asset performance vs solo content", benchmark: "Co-branded assets should outperform solo by ≥20% on lead volume" },
  { label: "Active partner retention", benchmark: "≥60% of Tier-1 partners renew for a second campaign" },
]

export default function CoMarketingCalendarPage() {
  return (
    <>
      <PageHero
        eyebrow="Co-Marketing Calendar"
        title="Build Partnerships That Grow Both Audiences with a Structured Co-Marketing Calendar"
        subtitle="Partner identification, campaign coordination, content co-creation, and performance reviews — all on one calendar that turns partnerships into a predictable growth channel."
        cta="Start free — forever"
        ctaHref="/sign-up"
      />

      {/* Pillar sections */}
      <section className="py-24" style={{ background: "#0a0a0d" }}>
        <div className="mx-auto max-w-6xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-16" style={{ color: "#f0ece3" }}>
              The Four Pillars of a Co-Marketing Calendar
            </h2>
          </Reveal>
          <div className="grid gap-8 md:grid-cols-2">
            {pillars.map(({ icon: Icon, title, body }) => (
              <Reveal key={title}>
                <div
                  className="rounded-xl p-8 h-full"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div
                    className="mb-4 inline-flex items-center justify-center rounded-lg p-3"
                    style={{ background: "rgba(197,163,92,0.12)" }}
                  >
                    <Icon size={22} style={{ color: "#c5a35c" }} />
                  </div>
                  <h3 className="mb-3 font-display text-xl font-semibold" style={{ color: "#f0ece3" }}>
                    {title}
                  </h3>
                  <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                    {body}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* 12-month plan */}
      <section className="py-24" style={{ background: "#0c0c0f" }}>
        <div className="mx-auto max-w-4xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-16" style={{ color: "#f0ece3" }}>
              12-Month Co-Marketing Calendar
            </h2>
          </Reveal>
          <div className="space-y-6">
            {timeline.map(({ phase, label, description }) => (
              <Reveal key={phase}>
                <div
                  className="rounded-xl p-8"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div className="flex items-start gap-6">
                    <div className="shrink-0">
                      <span
                        className="inline-block rounded-lg px-3 py-1 text-xs font-semibold"
                        style={{ background: "rgba(197,163,92,0.15)", color: "#c5a35c" }}
                      >
                        {phase}
                      </span>
                    </div>
                    <div>
                      <h3 className="mb-2 font-display text-lg font-semibold" style={{ color: "#f0ece3" }}>
                        {label}
                      </h3>
                      <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                        {description}
                      </p>
                    </div>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* KPIs */}
      <section className="py-24" style={{ background: "#0a0a0d" }}>
        <div className="mx-auto max-w-5xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-4" style={{ color: "#f0ece3" }}>
              Co-Marketing Performance Benchmarks
            </h2>
            <p className="text-center mb-12 text-sm" style={{ color: "#8b8b8b" }}>
              Track these six metrics per partnership to identify which co-marketing relationships are worth expanding.
            </p>
          </Reveal>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {metrics.map(({ label, benchmark }) => (
              <Reveal key={label}>
                <div
                  className="rounded-xl p-6"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <p className="text-xs font-semibold uppercase tracking-widest mb-2" style={{ color: "#c5a35c" }}>
                    {label}
                  </p>
                  <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                    {benchmark}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonial */}
      <section className="py-24" style={{ background: "#0c0c0f" }}>
        <div className="mx-auto max-w-2xl px-6 text-center">
          <Reveal>
            <blockquote
              className="mb-6 font-display text-2xl font-medium leading-snug"
              style={{ color: "#f0ece3" }}
            >
              &ldquo;Co-marketing became our highest-ROAS channel — lower than paid, higher lead quality than SEO. The calendar made the difference: a structured cadence forced us to run one partnership every quarter instead of opportunistically, and the compounding effect was dramatic.&rdquo;
            </blockquote>
            <p className="text-sm font-semibold" style={{ color: "#c5a35c" }}>
              Sasha K.
            </p>
            <p className="text-xs mt-1" style={{ color: "#8b8b8b" }}>
              Head of Partnerships, B2B SaaS (24 co-marketing campaigns in 2 years)
            </p>
          </Reveal>
        </div>
      </section>

      <CTA
        title="Schedule your co-marketing calendar in minutes"
        subtitle="Momenties keeps every partner campaign, content deadline, and distribution date in one place — free forever."
        cta="Get started free"
        href="/sign-up"
      />
    </>
  )
}
