import type { MetadataRoute } from 'next'
import { BLOG_POSTS } from '@/lib/blog-posts'
import { COMPETITORS } from '@/lib/competitors'
import { HELP_ARTICLES } from '@/lib/help-articles'
import { CUSTOMER_STORIES } from '@/lib/customers'
import { JOBS } from '@/lib/jobs'
import { INTEGRATIONS as DETAILED_INTEGRATIONS } from '@/lib/integrations'
import { allEntries as allReleases } from '@/lib/changelog'
import { AUTHORS } from '@/lib/authors'
import { USE_CASES } from '@/lib/use-cases'
import { ENDPOINTS as API_ENDPOINTS } from '@/lib/api-endpoints'
import { EPISODES as PODCAST_EPISODES } from '@/lib/podcast'

const BASE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://momenties.app'

const STATIC_PATHS: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'] }[] = [
  { path: '/', priority: 1, changeFrequency: 'weekly' },
  { path: '/features', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/pricing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/pricing/calculator', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/demo', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/compare', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/switch', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/integrations', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/enterprise', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/startups', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/education', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/customers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/wall-of-love', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/trust', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/use-cases', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/templates', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/about', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/manifesto', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/method', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/uses', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/careers', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/contact', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/security', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/security/report', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/blog', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/changelog', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/launch-week-1', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/year-in-review', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/roadmap', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/labs', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/help', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/learn', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/keyboard', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/downloads', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/api-docs', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/community', priority: 0.5, changeFrequency: 'weekly' },
  { path: '/webinars', priority: 0.5, changeFrequency: 'weekly' },
  { path: '/podcast', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/glossary', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/sitemap', priority: 0.3, changeFrequency: 'monthly' },
  { path: '/status', priority: 0.5, changeFrequency: 'daily' },
  { path: '/press', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/brand', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/affiliates', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/ambassadors', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/partners', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/investors', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/open', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/pro', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/speed', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/impact', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/sla', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/getting-started', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/design', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/refund', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/free', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/feedback', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/schedule', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/api', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/gift', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/waitlist', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/daily-brief', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/compare/price', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/features/voice', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/google-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/features/analytics', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/engineering-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/freelancers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/focus-mode', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/natural-language-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/founders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/team-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/best-calendar-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/students', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai/ethics', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/product-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-remote-teams', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/time-blocking', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/outlook-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai-scheduling', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/calendar-app-for-iphone', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/designers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/deep-work', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/work-life-balance', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/meeting-overload', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/executives', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-sync', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/lawyers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/smart-scheduling', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-templates', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/consultants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/recurring-events', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/productivity-tips', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/teachers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/voice-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/sales', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-adhd', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/fantastical-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/cron-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/motion-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/writers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/apple-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/accountants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/reclaim-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/shared-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/coaches', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/personal-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/work-from-home-schedule', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/event-planning-app', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-privacy', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/real-estate-agents', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-couples', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/athletes', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai-daily-planner', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/schedule-maker', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pastors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/meeting-scheduler', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/free-calendar-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/doctors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/weekly-planner', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/musicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/daily-schedule-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/time-management-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/google-calendar-vs-outlook', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/project-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/personal-trainers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-families', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/social-media-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/productivity-system', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/videographers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai-calendar-assistant', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/appointment-scheduling', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/nutritionists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-integration', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/journalists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/photographers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/architects', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/student-planner', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/financial-advisors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/marketing-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-tips', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/recruiters', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/event-coordinators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/work-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/freelance-developers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/dentists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/time-audit', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/virtual-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/best-productivity-apps', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/chiropractors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/team-productivity', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/optometrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-chrome-extension', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pharmacists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/focus-time', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/calendar-app-for-android', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/physical-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/speech-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/morning-routine', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/occupational-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/productivity-planner', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/social-workers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-hacks', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/dietitians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/smart-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/paralegals', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/online-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/massage-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/task-management-vs-calendar', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/yoga-instructors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-entrepreneurs', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/meeting-free-day', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/acupuncturists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-blocking', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/real-estate-investors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai-scheduling-assistant', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/insurance-agents', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/wedding-planners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-managers', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/financial-planners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/copywriters', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/deep-work-schedule', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/graphic-designers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/time-zone-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/interior-designers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/data-scientists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/habit-tracker-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/cybersecurity-professionals', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pomodoro-timer-app', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/ux-researchers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/executive-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/weekly-review', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/physical-education-teachers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/google-calendar-tips', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/calendar-notifications', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/school-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/time-management-strategies', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/daily-planner-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/veterinarians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-students', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/life-coaches', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/work-life-integration', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/engineers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-sharing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/inbox-zero-calendar', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/content-creators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-psychologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/quarter-planning', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/school-principals', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/async-work-calendar', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-creatives', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/energy-management-calendar', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/accountants-cpa', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/emergency-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/family-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatricians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nonprofit-directors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/business-owners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/goal-setting-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/productivity-coaches', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/anesthesiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/annual-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/radiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/batch-processing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/professors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/loan-officers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/business-analysts', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/time-boxing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/human-resources-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-anxiety', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/supply-chain-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/morning-routine-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/it-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/two-minute-rule-calendar', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/tax-preparers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/compliance-officers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-seniors', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/therapists-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/no-meeting-wednesday', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/orthodontists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/focus-blocks', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/physical-therapists-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-review', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/registered-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nurse-practitioners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/physician-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/dental-hygienists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/respiratory-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/sprint-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/dermatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/podiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/okr-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/medical-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/editorial-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/gastroenterologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/meeting-cadence', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pharmacy-technicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/case-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/project-timeline-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/tax-deadline-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/obstetricians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/radiologic-technologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/emts-paramedics', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/athletic-trainers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/habit-stacking-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/occupational-therapy-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/surgical-technologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/medical-coders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/school-psychologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/delegation-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/health-coaches', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/mental-health-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/art-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/health-information-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/accountability-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/dietetic-technicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/music-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/recreational-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/kinesiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/conference-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/certified-nursing-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/genetic-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-laboratory-scientists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/reading-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/diagnostic-medical-sonographers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/personal-development-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/perfusionists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/polysomnographic-technologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-social-workers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/marriage-family-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/certified-diabetes-educators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/wound-care-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/skills-development-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/orthotists-prosthetists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/public-health-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/budget-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/certified-professional-coders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pain-management-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/infectious-disease-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/rheumatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/endocrinologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-nurse-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nurse-anesthetists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cytotechnologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/vendor-management-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/midwives', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/palliative-care-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sleep-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/interview-prep-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hospice-workers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/radiologic-technologists-ct', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/medical-billing-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/health-unit-coordinators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/project-retrospective-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/nuclear-medicine-technologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sterile-processing-technicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/onboarding-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/addiction-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/radiologists-interventional', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cardiac-sonographers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-pharmacists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/performance-review-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/medical-device-sales-reps', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/patient-navigators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nephrology-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/sales-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/vascular-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/thoracic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/colorectal-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/transplant-coordinators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/networking-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hand-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/orthopedic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/oral-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/health-educators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/budget-review-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/urologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neurosurgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-research-coordinators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/launch-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/ophthalmologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/plastic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/hiring-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/sports-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neonatal-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/travel-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/critical-care-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/oncology-pharmacists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/client-onboarding-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/infection-control-practitioners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/dialysis-technicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/speaking-preparation-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/anesthesiologist-assistants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/radiation-therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/perioperative-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nuclear-pharmacists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/mentorship-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-documentation-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/lactation-consultants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cardiovascular-technologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/book-writing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/rehabilitation-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/medical-examiners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/toxicologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/product-launch-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/epidemiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/health-physicists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/investor-relations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/biomedical-engineers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/imaging-informatics-professionals', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/transplant-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-strategy-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-ethicists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/interventional-cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/partnership-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hospice-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-nurse-educators', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sports-dietitians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/trauma-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/research-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/neonatal-nurse-practitioners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/dermatology-nurse-practitioners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/forensic-pathologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/conference-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/oral-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hand-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/critical-care-pharmacists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/fundraising-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/vascular-interventional-radiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neuro-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/aesthetic-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/customer-success-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/maternal-fetal-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/psychiatric-nurse-practitioners', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/board-meeting-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/geriatric-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/oral-maxillofacial-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hematologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/media-relations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/addiction-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/burn-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/productivity-audit-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/immunologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/colon-rectal-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/client-retention-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hospice-and-palliative-care-nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/transplant-hepatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/team-meeting-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-pharmacists-ambulatory', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/sales-forecast-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-genetic-counselors', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/endovascular-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/product-roadmap-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-emergency-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-intensivists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/remote-team-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-pulmonologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neurocritical-care-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-informatics-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neuroradiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/continuing-education-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/sports-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hepatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/investor-update-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/gynecologic-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/reproductive-endocrinologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/freelance-client-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/urogynecologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-rheumatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/accountability-partner-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-hematologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/transplant-nephrologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-repurposing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-gastroenterologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/critical-care-pulmonologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/speaking-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-endocrinologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/vascular-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/annual-review-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/interventional-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-nephrologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/client-check-in-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/geriatric-cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-infectious-disease-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/job-search-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-allergists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/habit-formation-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/medical-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-dermatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/side-project-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-neurophysiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/launch-checklist-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-neurodevelopmental-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/team-offsite-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/cardiac-electrophysiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/forensic-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/addiction-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/quarterly-business-review-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/obesity-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sports-cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/design-sprint-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/transplant-pulmonologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neuro-ophthalmologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/one-on-one-meeting-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/reproductive-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/adolescent-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/lifestyle-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/crisis-communication-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/adult-congenital-heart-disease-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/headache-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/multiple-sclerosis-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/movement-disorder-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/investor-pitch-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/vascular-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neuro-intensivists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-neurophysiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/annual-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-intensivists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/geriatric-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-rheumatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/social-media-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/interventional-radiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/neonatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/email-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-ophthalmologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/interventional-pulmonologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pr-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hepato-pancreato-biliary-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sports-medicine-orthopedic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/influencer-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/craniofacial-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/maxillofacial-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/bariatric-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/podcast-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/glaucoma-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cornea-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/retina-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/webinar-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/colorectal-cancer-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/thoracic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/endocrine-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/seo-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/vascular-surgeons-endovascular', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/microsurgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/affiliate-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/congenital-heart-disease-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/community-building-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/facial-plastic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/customer-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-urology-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/video-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/spine-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/event-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/colorectal-fistula-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/paid-media-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/abdominal-wall-reconstruction-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/growth-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-oncology-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/social-media-content-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/otolaryngologists-head-neck', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/brand-awareness-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/minimally-invasive-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/demand-generation-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/acute-care-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/product-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/gynecologic-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/launch-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/urogynecologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/co-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/surgical-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-distribution-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/liver-transplant-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hyperbaric-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/audience-building-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/newsletter-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/cardiac-anesthesiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-anesthesiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/partnership-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/thought-leadership-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/neuro-oncologists-surgeons', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/medical-toxicologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/account-based-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/customer-journey-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-neuropsychologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/transplant-cardiologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/retention-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/lifecycle-email-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/neuro-interventionalists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/radiation-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/conversion-rate-optimization-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/sales-enablement-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pulmonary-hypertension-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/cystic-fibrosis-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/community-led-growth-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/product-led-growth-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/allergy-immunologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/interventional-pain-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/revenue-operations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/customer-success-operations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/maternal-fetal-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/developmental-pediatricians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pricing-strategy-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/go-to-market-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/geriatric-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sports-rehabilitation-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/influencer-relations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/brand-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/clinical-lipidologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/occupational-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/social-selling-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/analyst-relations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/transplant-infectious-disease-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/critical-care-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/field-marketing-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/competitive-intelligence-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/perinatal-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/headache-neurologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/customer-advocacy-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/sales-kickoff-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/cornea-transplant-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/pediatric-rheumatologists-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/revenue-recognition-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/enterprise-sales-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/bariatric-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/integrative-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/board-meeting-prep-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/strategic-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/aesthetic-dermatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-neuropsychologists-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/media-buying-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/fundraising-operations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/vascular-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/hematology-oncologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/procurement-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/legal-operations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pediatric-palliative-care-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/clinical-pharmacologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/cybersecurity-operations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/engineering-planning-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/pain-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/sports-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/data-governance-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/hr-compliance-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/occupational-medicine-physicians', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/geriatric-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/product-launch-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/investor-relations-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/child-adolescent-psychiatrists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/reproductive-endocrinologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/content-strategy-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/partnership-development-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/neonatologists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/addiction-medicine-specialists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/pricing-strategy-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/customer-success-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/features/photo', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/cancel', priority: 0.4, changeFrequency: 'yearly' },
  { path: '/ai/policy', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/why', priority: 0.8, changeFrequency: 'yearly' },
  { path: '/teams', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/product', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/mobile', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/cli', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/developers', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/newsletter', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/data', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/authors', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/search', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/accessibility', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/subprocessors', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' },
  { path: '/terms', priority: 0.3, changeFrequency: 'yearly' },
  { path: '/cookies', priority: 0.3, changeFrequency: 'yearly' },
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    ...STATIC_PATHS.map((p) => ({
      url: `${BASE}${p.path}`,
      lastModified: now,
      changeFrequency: p.changeFrequency,
      priority: p.priority,
    })),
    ...BLOG_POSTS.map((post) => ({
      url: `${BASE}/blog/${post.slug}`,
      lastModified: new Date(post.date),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
    ...COMPETITORS.map((c) => ({
      url: `${BASE}/compare/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...HELP_ARTICLES.map((a) => ({
      url: `${BASE}/help/${a.categorySlug}/${a.slug}`,
      lastModified: new Date(a.updated),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    ...CUSTOMER_STORIES.map((c) => ({
      url: `${BASE}/customers/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...JOBS.map((j) => ({
      url: `${BASE}/careers/${j.slug}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    })),
    ...DETAILED_INTEGRATIONS.map((i) => ({
      url: `${BASE}/integrations/${i.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...allReleases().map((e) => ({
      url: `${BASE}/changelog/${e.version}`,
      lastModified: new Date(e.date),
      changeFrequency: 'yearly' as const,
      priority: 0.4,
    })),
    ...['productivity', 'ai', 'design', 'time', 'engineering', 'company'].map((cat) => ({
      url: `${BASE}/blog/category/${cat}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    })),
    ...AUTHORS.map((a) => ({
      url: `${BASE}/authors/${a.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.4,
    })),
    ...USE_CASES.map((u) => ({
      url: `${BASE}/use-cases/${u.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...API_ENDPOINTS.map((e) => ({
      url: `${BASE}/api-docs/${e.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    ...PODCAST_EPISODES.map((e) => ({
      url: `${BASE}/podcast/${e.slug}`,
      lastModified: new Date(e.publishedAt),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
  ]
}
