import type { MetadataRoute } from 'next'
import { BLOG_POSTS } from '@/lib/blog-posts'
import { COMPETITORS } from '@/lib/competitors'
import { HELP_ARTICLES } from '@/lib/help-articles'
import { CUSTOMER_STORIES } from '@/lib/customers'
import { JOBS } from '@/lib/jobs'
import { INTEGRATIONS as DETAILED_INTEGRATIONS } from '@/lib/integrations'
import { allEntries as allReleases } from '@/lib/changelog'
import { AUTHORS } from '@/lib/authors'
import { USE_CASES } from '@/lib/use-cases'
import { ENDPOINTS as API_ENDPOINTS } from '@/lib/api-endpoints'
import { EPISODES as PODCAST_EPISODES } from '@/lib/podcast'

const BASE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://momenties.app'

const STATIC_PATHS: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]['changeFrequency'] }[] = [
  { path: '/', priority: 1, changeFrequency: 'weekly' },
  { path: '/features', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/pricing', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/pricing/calculator', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/demo', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/compare', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/switch', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/integrations', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/enterprise', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/startups', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/education', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/customers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/wall-of-love', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/trust', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/use-cases', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/templates', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/about', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/manifesto', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/method', priority: 0.6, changeFrequency: 'yearly' },
  { path: '/uses', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/careers', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/contact', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/security', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/security/report', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/blog', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/changelog', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/launch-week-1', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/year-in-review', priority: 0.7, changeFrequency: 'yearly' },
  { path: '/roadmap', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/labs', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/help', priority: 0.6, changeFrequency: 'weekly' },
  { path: '/learn', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/keyboard', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/downloads', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/api-docs', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/community', priority: 0.5, changeFrequency: 'weekly' },
  { path: '/webinars', priority: 0.5, changeFrequency: 'weekly' },
  { path: '/podcast', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/glossary', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/sitemap', priority: 0.3, changeFrequency: 'monthly' },
  { path: '/status', priority: 0.5, changeFrequency: 'daily' },
  { path: '/press', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/brand', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/affiliates', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/ambassadors', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/partners', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/investors', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/open', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/pro', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/speed', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/impact', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/sla', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/getting-started', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/design', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/refund', priority: 0.5, changeFrequency: 'yearly' },
  { path: '/free', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/feedback', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/schedule', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/api', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/gift', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/waitlist', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/daily-brief', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/compare/price', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/features/voice', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/google-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/features/analytics', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/engineering-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/freelancers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/focus-mode', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/natural-language-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/founders', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/team-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/best-calendar-app', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/students', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai/ethics', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/product-managers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-remote-teams', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/time-blocking', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/outlook-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/ai-scheduling', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/calendar-app-for-iphone', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/designers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/deep-work', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/work-life-balance', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/meeting-overload', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/executives', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-sync', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/lawyers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/smart-scheduling', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-templates', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/consultants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/recurring-events', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/productivity-tips', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/teachers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/voice-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/sales', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-adhd', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/fantastical-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/cron-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/motion-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/writers', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/apple-calendar-alternative', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/hr', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/accountants', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/reclaim-alternative', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/shared-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/for/coaches', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/therapists', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/personal-calendar', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/work-from-home-schedule', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/nurses', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/event-planning-app', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-privacy', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/for/real-estate-agents', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/calendar-for-couples', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/for/athletes', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/ai-daily-planner', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/schedule-maker', priority: 0.9, changeFrequency: 'monthly' },
  { path: '/features/photo', priority: 0.8, changeFrequency: 'monthly' },
  { path: '/cancel', priority: 0.4, changeFrequency: 'yearly' },
  { path: '/ai/policy', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/why', priority: 0.8, changeFrequency: 'yearly' },
  { path: '/teams', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/product', priority: 0.85, changeFrequency: 'monthly' },
  { path: '/mobile', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/cli', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/developers', priority: 0.7, changeFrequency: 'monthly' },
  { path: '/newsletter', priority: 0.7, changeFrequency: 'weekly' },
  { path: '/data', priority: 0.6, changeFrequency: 'monthly' },
  { path: '/authors', priority: 0.5, changeFrequency: 'monthly' },
  { path: '/search', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/accessibility', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/subprocessors', priority: 0.4, changeFrequency: 'monthly' },
  { path: '/privacy', priority: 0.3, changeFrequency: 'yearly' },
  { path: '/terms', priority: 0.3, changeFrequency: 'yearly' },
  { path: '/cookies', priority: 0.3, changeFrequency: 'yearly' },
]

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  return [
    ...STATIC_PATHS.map((p) => ({
      url: `${BASE}${p.path}`,
      lastModified: now,
      changeFrequency: p.changeFrequency,
      priority: p.priority,
    })),
    ...BLOG_POSTS.map((post) => ({
      url: `${BASE}/blog/${post.slug}`,
      lastModified: new Date(post.date),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
    ...COMPETITORS.map((c) => ({
      url: `${BASE}/compare/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...HELP_ARTICLES.map((a) => ({
      url: `${BASE}/help/${a.categorySlug}/${a.slug}`,
      lastModified: new Date(a.updated),
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    ...CUSTOMER_STORIES.map((c) => ({
      url: `${BASE}/customers/${c.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...JOBS.map((j) => ({
      url: `${BASE}/careers/${j.slug}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.6,
    })),
    ...DETAILED_INTEGRATIONS.map((i) => ({
      url: `${BASE}/integrations/${i.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...allReleases().map((e) => ({
      url: `${BASE}/changelog/${e.version}`,
      lastModified: new Date(e.date),
      changeFrequency: 'yearly' as const,
      priority: 0.4,
    })),
    ...['productivity', 'ai', 'design', 'time', 'engineering', 'company'].map((cat) => ({
      url: `${BASE}/blog/category/${cat}`,
      lastModified: now,
      changeFrequency: 'weekly' as const,
      priority: 0.5,
    })),
    ...AUTHORS.map((a) => ({
      url: `${BASE}/authors/${a.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.4,
    })),
    ...USE_CASES.map((u) => ({
      url: `${BASE}/use-cases/${u.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.7,
    })),
    ...API_ENDPOINTS.map((e) => ({
      url: `${BASE}/api-docs/${e.slug}`,
      lastModified: now,
      changeFrequency: 'monthly' as const,
      priority: 0.5,
    })),
    ...PODCAST_EPISODES.map((e) => ({
      url: `${BASE}/podcast/${e.slug}`,
      lastModified: new Date(e.publishedAt),
      changeFrequency: 'monthly' as const,
      priority: 0.6,
    })),
  ]
}
