import type { Metadata } from "next"
import { TrendingUp, Clock, BarChart3, Users } from "lucide-react"
import { PageHero } from "@/components/marketing/PageHero"
import { Reveal } from "@/components/marketing/Reveal"
import { CTA } from "@/components/marketing/CTA"

export const metadata: Metadata = {
  title: "Thought Leadership Calendar | Momenties",
  description: "Plan your thought leadership calendar with original research publishing, speaking cadences, media positioning, and authority tracking. Build the kind of credibility that compounds.",
}

const pillars = [
  {
    icon: TrendingUp,
    title: "Original Research & POV Content Calendar",
    body: "Thought leadership that compounds is built on original ideas, not curated content. Content calendar framework: 1 flagship original research piece per quarter (survey, proprietary data analysis, or benchmark report — takes 4-6 weeks to produce, drives backlinks and media mentions for 12+ months), 1 strong opinion piece per month (a specific position on a contested industry question — not a summary of what others think), and 2-3 shorter hot-take posts per week (responsive to industry news, draws on your unique perspective). Research calendar: survey design in month 1, data collection in month 2, analysis and writing in month 3, launch campaign in month 4 — flagship research requires a full quarter lead time. POV content calendar: maintain a running list of contested industry questions where your position is specific and defensible. Write the strongest counterargument first, then refute it — this is what makes thought leadership credible rather than just confident. Original research is the only content type that reliably earns unsolicited inbound speaking invitations, media mentions, and enterprise customer trust.",
  },
  {
    icon: Clock,
    title: "Speaking & Conference Calendar",
    body: "Speaking engagements drive thought leadership compounding at a different rate than written content — one well-placed keynote introduces you to 500-2,000 qualified professionals in 45 minutes. Conference calendar: 18-month rolling conference pipeline (abstract submission deadlines are typically 4-6 months before the event — missing the submission deadline means missing the event). Speaking tier strategy: 3-5 Tier 1 conferences per year (main stage keynote at industry flagship events — highest visibility), 4-6 Tier 2 (breakout session at industry conferences — high qualification), ongoing Tier 3 (podcasts, webinars, virtual events — volume play). Abstract submission calendar: for each target conference, add the abstract submission deadline as a non-negotiable calendar event 6 months before the event. Talk development calendar: title and abstract finalized 4 weeks before submission deadline, full presentation developed 6 weeks before event, rehearsals 2 weeks before. Talk recycling: each conference presentation becomes 3-4 pieces of written content within 1 week of the event.",
  },
  {
    icon: BarChart3,
    title: "Media Positioning & Analyst Relations Calendar",
    body: "Media positioning calendar: become the journalist&apos;s first call for your specific topic — not all technology topics, not your industry, but a specific intersection where you have demonstrably unique insight. Monthly media touchpoints: 1 original data point or survey result shared with 3-5 journalists covering your topic (not a pitch — a useful gift), 1 rapid response quote offered to journalists within 2 hours of relevant industry news breaking (be a reliable source on short notice). Analyst relations calendar: 2 annual analyst briefings (Gartner, Forrester, IDC — or niche analysts in your category), 1 annual EARS submission (analyst inquiry request where you brief the analyst proactively), quarterly analyst research sharing. Speaking at analyst events: Gartner Summit, Forrester Decisions — abstract deadline 3-4 months ahead. Earned media goal: by month 12, be quoted in 2-3 Tier 1 publications per quarter on your specific topic. Track share of voice quarterly (how often you appear in media coverage of your topic versus competitors).",
  },
  {
    icon: Users,
    title: "Authority Tracking & Thought Leadership Reviews Calendar",
    body: "Monthly thought leadership review (30 minutes): LinkedIn post performance (impressions, new followers from specific posts — which topics drove above-benchmark follower growth?), newsletter growth from original content versus curated content (original opinions consistently drive 2-3× more subscriber growth than curated), and inbound requests generated by content (speaking invitations, media interviews, enterprise sales introductions — these are the lagging indicators that confirm thought leadership is compounding). Quarterly authority audit (90 minutes): SEO ranking for your specific thought leadership topic (are you ranking for the contested questions in your niche?), share of voice in media coverage (are you quoted more or less than last quarter?), backlinks earned by original research (is flagship research earning links 3-6 months after publish?), and speaking pipeline (are conferences seeking you out, or are you still primarily applying?). Annual thought leadership strategy review: which positions drove the most inbound? Which positions lost relevance? Update your core 3-5 positions for the next year based on audience response data.",
  },
]

const timeline = [
  {
    phase: "Month 1",
    label: "Position Definition & Content Foundation",
    description:
      "Define 3-5 specific contested positions where your perspective is unique and defensible (not broad industry trends — specific positions on specific questions). Audit existing content for thought leadership signals. Identify target conferences with abstract submission deadlines for the next 12 months. Start first flagship research project (survey design phase). Commit to a weekly publishing cadence.",
  },
  {
    phase: "Month 2–3",
    label: "First Flagship Research & Speaking Applications",
    description:
      "Complete and publish first flagship research piece with launch campaign (email, social, media outreach). Submit first 3 conference abstracts. Complete first month of weekly POV content — measure which topics drive above-benchmark follower growth. Begin journalist relationship-building (share research, offer background briefings without pitches).",
  },
  {
    phase: "Month 4–6",
    label: "Media Momentum & Authority Building",
    description:
      "First media quote or mention from research launch. First speaking confirmation. Second quarterly research piece in production. Analyst briefing scheduled. Track SEO positions for your specific thought leadership keywords — identify which pieces are ranking and optimize. Conduct first quarterly authority audit.",
  },
  {
    phase: "Month 7–12",
    label: "Compounding & Inbound Transformation",
    description:
      "By month 9-12, inbound speaking invitations should begin exceeding outbound applications. Third and fourth quarterly research pieces published. Annual analyst briefing completed. Measure inbound enterprise sales introductions attributable to thought leadership. Annual strategy review: which positions drove the most commercial impact? Update core positions for year 2.",
  },
]

const metrics = [
  { label: "Media mentions per quarter", benchmark: "Target 3-5 Tier 1 media mentions per quarter by month 12 on your specific topic — not general industry coverage" },
  { label: "Speaking invitations vs applications", benchmark: "By year 2, ≥50% of speaking engagements should be inbound (you were sought) rather than outbound (you applied)" },
  { label: "Flagship research backlinks", benchmark: "Each flagship research piece should earn ≥20 referring domains within 6 months — track with Ahrefs or SEMrush" },
  { label: "Follower growth from original POV content", benchmark: "Original opinion posts should drive 2-3× more new followers per piece than curated or news-driven content" },
  { label: "Inbound pipeline from thought leadership", benchmark: "Track CRM source — thought leadership-attributed inbound pipeline should grow quarter-over-quarter" },
  { label: "Topic authority score", benchmark: "Quarterly: are you ranking for 2-3 key contested questions in your niche? Yes/no is the benchmark — then improve ranking" },
]

export default function ThoughtLeadershipCalendarPage() {
  return (
    <>
      <PageHero
        eyebrow="Thought Leadership Calendar"
        title="Build the Kind of Credibility That Compounds with a Structured Thought Leadership Calendar"
        subtitle="Original research publishing, speaking cadences, media positioning, and authority tracking — all on one calendar that turns consistent original thinking into compounding influence."
        cta="Start free — forever"
        ctaHref="/sign-up"
      />

      {/* Pillar sections */}
      <section className="py-24" style={{ background: "#0a0a0d" }}>
        <div className="mx-auto max-w-6xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-16" style={{ color: "#f0ece3" }}>
              The Four Pillars of a Thought Leadership Calendar
            </h2>
          </Reveal>
          <div className="grid gap-8 md:grid-cols-2">
            {pillars.map(({ icon: Icon, title, body }) => (
              <Reveal key={title}>
                <div
                  className="rounded-xl p-8 h-full"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div
                    className="mb-4 inline-flex items-center justify-center rounded-lg p-3"
                    style={{ background: "rgba(197,163,92,0.12)" }}
                  >
                    <Icon size={22} style={{ color: "#c5a35c" }} />
                  </div>
                  <h3 className="mb-3 font-display text-xl font-semibold" style={{ color: "#f0ece3" }}>
                    {title}
                  </h3>
                  <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                    {body}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* 12-month plan */}
      <section className="py-24" style={{ background: "#0c0c0f" }}>
        <div className="mx-auto max-w-4xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-16" style={{ color: "#f0ece3" }}>
              12-Month Thought Leadership Calendar
            </h2>
          </Reveal>
          <div className="space-y-6">
            {timeline.map(({ phase, label, description }) => (
              <Reveal key={phase}>
                <div
                  className="rounded-xl p-8"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <div className="flex items-start gap-6">
                    <div className="shrink-0">
                      <span
                        className="inline-block rounded-lg px-3 py-1 text-xs font-semibold"
                        style={{ background: "rgba(197,163,92,0.15)", color: "#c5a35c" }}
                      >
                        {phase}
                      </span>
                    </div>
                    <div>
                      <h3 className="mb-2 font-display text-lg font-semibold" style={{ color: "#f0ece3" }}>
                        {label}
                      </h3>
                      <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                        {description}
                      </p>
                    </div>
                  </div>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* KPIs */}
      <section className="py-24" style={{ background: "#0a0a0d" }}>
        <div className="mx-auto max-w-5xl px-6">
          <Reveal>
            <h2 className="text-center font-display text-3xl font-bold mb-4" style={{ color: "#f0ece3" }}>
              Thought Leadership Performance Benchmarks
            </h2>
            <p className="text-center mb-12 text-sm" style={{ color: "#8b8b8b" }}>
              Track these six metrics quarterly to measure whether your thought leadership is compounding in authority and commercial impact.
            </p>
          </Reveal>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {metrics.map(({ label, benchmark }) => (
              <Reveal key={label}>
                <div
                  className="rounded-xl p-6"
                  style={{ background: "#131318", border: "1px solid rgba(255,255,255,0.07)" }}
                >
                  <p className="text-xs font-semibold uppercase tracking-widest mb-2" style={{ color: "#c5a35c" }}>
                    {label}
                  </p>
                  <p className="text-sm leading-relaxed" style={{ color: "#8b8b8b" }}>
                    {benchmark}
                  </p>
                </div>
              </Reveal>
            ))}
          </div>
        </div>
      </section>

      {/* Testimonial */}
      <section className="py-24" style={{ background: "#0c0c0f" }}>
        <div className="mx-auto max-w-2xl px-6 text-center">
          <Reveal>
            <blockquote
              className="mb-6 font-display text-2xl font-medium leading-snug"
              style={{ color: "#f0ece3" }}
            >
              &ldquo;The thought leadership calendar changed one thing that changed everything: it forced me to publish original research quarterly instead of whenever I felt inspired. The first flagship report took six weeks and drove more inbound in 90 days than six months of curated content. By year two, I was turning down more speaking invitations than I was accepting. The calendar made it systematic, not heroic.&rdquo;
            </blockquote>
            <p className="text-sm font-semibold" style={{ color: "#c5a35c" }}>
              Ben A.
            </p>
            <p className="text-xs mt-1" style={{ color: "#8b8b8b" }}>
              Founder & CEO, B2B SaaS (4 Tier 1 media mentions per quarter, 12K LinkedIn followers in 18 months)
            </p>
          </Reveal>
        </div>
      </section>

      <CTA
        title="Schedule your thought leadership calendar in minutes"
        subtitle="Momenties keeps every research deadline, conference abstract submission, media touchpoint, and authority review in one place — free forever."
        cta="Get started free"
        href="/sign-up"
      />
    </>
  )
}
