import type { Metadata } from "next"
import { Target, RefreshCw, TrendingUp, BarChart3 } from "lucide-react"
import { PageHero } from "@/components/marketing/PageHero"
import { Reveal } from "@/components/marketing/Reveal"
import { CTA } from "@/components/marketing/CTA"

export const metadata: Metadata = {
  title: "Marketing Operations Calendar | Momenties",
  description: "Build a systematic marketing operations calendar — MarTech stack audits, campaign attribution reviews, lead scoring model updates, database hygiene cycles, and marketing performance reporting cadences that increase pipeline quality and reduce wasted spend.",
}

const pillars = [
  {
    icon: Target,
    title: "MarTech Stack Audits & Integration Health Calendar",
    description:
      "Marketing technology sprawl is the silent killer of marketing operations — 60% of purchased MarTech tools are underutilized within 12 months, and broken integrations corrupt attribution data that informs budget decisions. Momenties schedules quarterly MarTech stack utilization reviews (identifying underused tools before renewal cycles), bi-annual integration health audits (verifying CRM-to-MAP data sync, lead routing rules, and field mapping accuracy), and annual MarTech vendor contract reviews timed 90 days before renewal dates. API rate limit monitoring, webhook failure alerts, and data sync lag reviews are managed weekly. Vendor-specific certification renewals — HubSpot Operations Hub, Salesforce Marketing Cloud, Marketo Engage — are tracked per tool with renewal windows.",
  },
  {
    icon: RefreshCw,
    title: "Lead Scoring Model Updates & Database Hygiene Cycles",
    description:
      "Lead scoring models built at launch become liabilities within 6 months — ICP shifts, product changes, and new competitor positioning invalidate the behavioral signals that defined qualified leads. Momenties schedules quarterly lead scoring model audits (comparing MQL-to-SQL conversion rates by lead score tier against closed-won data), semi-annual ICP definition reviews with sales leadership, and annual complete lead scoring model rebuilds aligned to revenue data. Database hygiene cadences — monthly duplicate detection and merge, quarterly bounce management and email validation, bi-annual full contact record audit against LinkedIn/ZoomInfo for title and company accuracy — prevent deliverability decay and keep segmentation reliable. GDPR/CCPA consent record audits are scheduled quarterly.",
  },
  {
    icon: TrendingUp,
    title: "Campaign Attribution Methodology & UTM Governance Calendar",
    description:
      "Attribution models without governance decay into chaos — UTM parameters become inconsistent, multi-touch attribution weights become stale, and finance loses confidence in marketing&apos;s revenue contribution claims. Momenties schedules monthly UTM hygiene reviews (auditing new campaigns for parameter compliance against the governance taxonomy), quarterly attribution model calibration sessions (comparing first-touch, last-touch, and multi-touch models against pipeline velocity data), and annual attribution methodology reviews where the marketing and finance team align on revenue credit rules. Dark funnel measurement programs — intent data, direct mail response tracking, podcast attribution — are reviewed semi-annually. Marketing mix modeling (MMM) refreshes are aligned to budget planning cycles.",
  },
  {
    icon: BarChart3,
    title: "Marketing Performance Reporting & Budget Pacing Calendar",
    description:
      "Marketing reporting without a cadence means finance gets surprises and marketing loses credibility. Momenties schedules weekly budget pacing dashboards (spend-to-date vs. plan, CPL by channel, pipeline generated by channel), monthly marketing performance reviews with CMO and finance (CAC by channel, LTV:CAC ratio, MQL-to-SQL conversion by source), and quarterly board-level marketing contribution reports (pipeline generated, revenue influenced, brand health metrics). Annual marketing attribution audits — presenting the relationship between marketing investment and revenue outcomes — are timed for budget planning season. Channel efficiency reports (paid social, search, content, events, ABM) are reviewed monthly with channel owners and quarterly with leadership.",
  },
]

const timeline = [
  {
    month: "Month 1–2",
    title: "MarTech Audit & Attribution Architecture",
    description: "Audit full MarTech stack utilization and integration health; document all active UTM governance rules; run baseline lead scoring model audit against closed-won data; establish weekly budget pacing dashboard; map all vendor renewal dates.",
  },
  {
    month: "Month 3",
    title: "Database Hygiene Sprint & Lead Scoring Model Update",
    description: "Run first full database hygiene cycle (deduplication, bounce management, email validation); update lead scoring model with Q1 MQL-to-SQL conversion data; implement UTM governance taxonomy; launch weekly attribution review.",
  },
  {
    month: "Month 4–5",
    title: "Attribution Calibration & ICP Review",
    description: "Run first quarterly attribution model calibration with sales and finance; review ICP definition against Q1-Q2 closed-won data; complete GDPR/CCPA consent record audit; launch monthly marketing performance reporting cadence.",
  },
  {
    month: "Month 6",
    title: "Mid-Year MarTech Contract Review & Performance Audit",
    description: "Review all MarTech tools with renewal in H2 (cancel underperforming tools before auto-renewal); run mid-year pipeline-to-investment attribution report; update channel efficiency benchmarks; run integration health audit.",
  },
  {
    month: "Month 7–9",
    title: "Annual Attribution Methodology Review & MMM Refresh",
    description: "Run annual attribution methodology alignment with finance; refresh marketing mix model with H1 spend and pipeline data; complete semi-annual dark funnel measurement review; launch annual lead scoring model rebuild project.",
  },
  {
    month: "Month 10–12",
    title: "Budget Planning Support & Annual MarTech Review",
    description: "Present annual marketing attribution and ROI report for budget planning; complete full MarTech stack rationalization; run annual database audit; lock UTM governance taxonomy and attribution model for next year; finalize MarTech contract renewals.",
  },
]

const kpis = [
  {
    metric: "MQL-to-SQL Conversion Rate",
    target: "≥ 25% conversion",
    description: "Percentage of MQLs accepted by sales as SQLs — below 15% indicates lead scoring model misalignment with sales ICP; above 30% may indicate scoring threshold is too conservative, leaving pipeline volume on the table.",
  },
  {
    metric: "Database Health Score",
    target: "≥ 90% valid records",
    description: "Percentage of contact records with valid email, current company, and complete lead source — below 80% health score causes deliverability decay, inaccurate segmentation, and unreliable attribution reporting.",
  },
  {
    metric: "UTM Parameter Compliance",
    target: "100% of paid campaigns tagged",
    description: "Percentage of active campaigns with correct UTM parameters per governance taxonomy — any untagged spend creates dark pipeline and distorts channel attribution, leading to budget misallocation decisions.",
  },
  {
    metric: "MarTech Utilization Rate",
    target: "≥ 70% of licensed tools",
    description: "Percentage of MarTech tools actively used by marketing team in the trailing quarter — below 50% utilization indicates shelfware; the average marketing team wastes 35% of MarTech budget on unused tools.",
  },
  {
    metric: "Attribution Report Accuracy",
    target: "≤ 5% variance vs. CRM",
    description: "Variance between marketing attribution report pipeline and CRM-recorded pipeline — above 10% variance triggers finance distrust of marketing contribution metrics and complicates budget justification.",
  },
  {
    metric: "Budget Pacing Accuracy",
    target: "Within ±5% of monthly plan",
    description: "Monthly actual spend vs. plan variance by channel — above ±10% variance indicates campaign pacing failures; underspend wastes demand gen capacity while overspend triggers finance escalations.",
  },
]

const testimonial = {
  quote:
    "Our MarTech stack had 34 tools, 12 broken integrations, a lead scoring model from 2021, and UTM parameters that were 40% non-compliant. Finance didn&apos;t trust our attribution numbers. Momenties gave us a structured operations calendar. We cut to 19 tools, rebuilt lead scoring with actual closed-won data, and for the first time finance accepted our pipeline attribution in the board deck.",
  name: "Yewande B.",
  title: "VP Marketing Operations, Series D Enterprise SaaS",
}

export default function MarketingOperationsCalendarPage() {
  return (
    <main style={{ background: "#0c0c0f", minHeight: "100vh" }}>
      <PageHero
        eyebrow="Marketing Operations Calendar"
        title="Clean Database. Trusted Attribution. MarTech That Actually Works."
        subtitle="A systematic marketing operations calendar with quarterly MarTech stack audits, lead scoring model updates, UTM governance reviews, database hygiene cycles, and attribution calibration cadences that increase pipeline quality and give finance confidence in marketing&apos;s revenue contribution."
      />

      {/* Pillars */}
      <Reveal>
        <section style={{ maxWidth: 1100, margin: "0 auto", padding: "80px 24px 0" }}>
          <h2
            style={{
              textAlign: "center",
              fontSize: "clamp(1.6rem, 3vw, 2.2rem)",
              fontWeight: 700,
              color: "#f0ece3",
              marginBottom: 48,
            }}
          >
            Four Systems That Build Marketing Operations Excellence
          </h2>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
              gap: 24,
            }}
          >
            {pillars.map((p) => (
              <div
                key={p.title}
                style={{
                  background: "#131318",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: 16,
                  padding: 28,
                }}
              >
                <p.icon size={28} color="#c5a35c" style={{ marginBottom: 16 }} />
                <h3 style={{ color: "#f0ece3", fontSize: "1.05rem", fontWeight: 600, marginBottom: 12 }}>
                  {p.title}
                </h3>
                <p style={{ color: "rgba(240,236,227,0.65)", fontSize: "0.92rem", lineHeight: 1.65 }}>
                  {p.description}
                </p>
              </div>
            ))}
          </div>
        </section>
      </Reveal>

      {/* 12-Month Timeline */}
      <Reveal>
        <section style={{ maxWidth: 900, margin: "0 auto", padding: "80px 24px 0" }}>
          <h2
            style={{
              textAlign: "center",
              fontSize: "clamp(1.6rem, 3vw, 2.2rem)",
              fontWeight: 700,
              color: "#f0ece3",
              marginBottom: 48,
            }}
          >
            Your 12-Month Marketing Operations Roadmap
          </h2>
          <div style={{ display: "flex", flexDirection: "column", gap: 20 }}>
            {timeline.map((t, i) => (
              <div
                key={i}
                style={{
                  display: "grid",
                  gridTemplateColumns: "140px 1fr",
                  gap: 24,
                  background: "#131318",
                  border: "1px solid rgba(255,255,255,0.07)",
                  borderRadius: 12,
                  padding: "20px 24px",
                  alignItems: "start",
                }}
              >
                <span style={{ color: "#c5a35c", fontWeight: 600, fontSize: "0.9rem", paddingTop: 2 }}>
                  {t.month}
                </span>
                <div>
                  <p style={{ color: "#f0ece3", fontWeight: 600, marginBottom: 6 }}>{t.title}</p>
                  <p style={{ color: "rgba(240,236,227,0.65)", fontSize: "0.9rem", lineHeight: 1.6 }}>
                    {t.description}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </section>
      </Reveal>

      {/* KPIs */}
      <Reveal>
        <section style={{ maxWidth: 1100, margin: "0 auto", padding: "80px 24px 0" }}>
          <h2
            style={{
              textAlign: "center",
              fontSize: "clamp(1.6rem, 3vw, 2.2rem)",
              fontWeight: 700,
              color: "#f0ece3",
              marginBottom: 48,
            }}
          >
            KPIs That Define Marketing Operations Maturity
          </h2>
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(260px, 1fr))",
              gap: 20,
            }}
          >
            {kpis.map((k) => (
              <div
                key={k.metric}
                style={{
                  background: "#0a0a0d",
                  border: "1px solid rgba(197,163,92,0.2)",
                  borderRadius: 12,
                  padding: 24,
                }}
              >
                <p style={{ color: "#c5a35c", fontWeight: 700, fontSize: "1.1rem", marginBottom: 4 }}>
                  {k.target}
                </p>
                <p style={{ color: "#f0ece3", fontWeight: 600, marginBottom: 8 }}>{k.metric}</p>
                <p style={{ color: "rgba(240,236,227,0.6)", fontSize: "0.88rem", lineHeight: 1.6 }}>
                  {k.description}
                </p>
              </div>
            ))}
          </div>
        </section>
      </Reveal>

      {/* Testimonial */}
      <Reveal>
        <section style={{ maxWidth: 720, margin: "0 auto", padding: "80px 24px 0" }}>
          <blockquote
            style={{
              background: "#131318",
              border: "1px solid rgba(197,163,92,0.25)",
              borderRadius: 16,
              padding: "36px 40px",
              textAlign: "center",
            }}
          >
            <p
              style={{
                color: "rgba(240,236,227,0.85)",
                fontSize: "1.05rem",
                lineHeight: 1.75,
                fontStyle: "italic",
                marginBottom: 24,
              }}
            >
              &ldquo;{testimonial.quote}&rdquo;
            </p>
            <p style={{ color: "#c5a35c", fontWeight: 600 }}>{testimonial.name}</p>
            <p style={{ color: "rgba(240,236,227,0.5)", fontSize: "0.88rem" }}>{testimonial.title}</p>
          </blockquote>
        </section>
      </Reveal>

      <div style={{ padding: "80px 0 0" }}>
        <CTA />
      </div>
    </main>
  )
}
